use crate::db::models::*;
use tauri::State;
use super::notebooks::AppState;

fn pt(t: &str) -> String { t.to_string() }
fn types(ts: &[&str]) -> Vec<String> { ts.iter().map(|t| t.to_string()).collect() }
fn docs(u: &str) -> Option<String> { Some(u.to_string()) }

#[tauri::command]
pub async fn get_providers(
    _state: State<'_, AppState>,
) -> Result<Vec<ProviderInfo>, String> {
    Ok(vec![
        ProviderInfo {
            name: pt("openai"),
            display_name: pt("OpenAI"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["language", "embedding", "text_to_speech", "speech_to_text"]),
            docs_url: docs("https://platform.openai.com/docs"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("anthropic"),
            display_name: pt("Anthropic"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["language"]),
            docs_url: docs("https://docs.anthropic.com"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("google"),
            display_name: pt("Google AI"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["language", "embedding", "text_to_speech", "speech_to_text"]),
            docs_url: docs("https://ai.google.dev"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("groq"),
            display_name: pt("Groq"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["language", "speech_to_text"]),
            docs_url: docs("https://console.groq.com/docs"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("mistral"),
            display_name: pt("Mistral AI"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["language", "embedding", "speech_to_text", "text_to_speech"]),
            docs_url: docs("https://docs.mistral.ai"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("deepseek"),
            display_name: pt("DeepSeek"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["language"]),
            docs_url: docs("https://platform.deepseek.com/docs"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("xai"),
            display_name: pt("xAI (Grok)"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["language", "text_to_speech"]),
            docs_url: docs("https://docs.x.ai"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("openrouter"),
            display_name: pt("OpenRouter"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["language", "embedding", "text_to_speech", "speech_to_text"]),
            docs_url: docs("https://openrouter.ai/docs"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("dashscope"),
            display_name: pt("DashScope (Qwen)"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["language"]),
            docs_url: docs("https://help.aliyun.com/zh/model-studio"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("minimax"),
            display_name: pt("MiniMax"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["language"]),
            docs_url: docs("https://platform.minimaxi.com/document"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("novita"),
            display_name: pt("Novita"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["language"]),
            docs_url: docs("https://novita.ai/docs"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("ppq"),
            display_name: pt("PayPerQ"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["language", "embedding", "text_to_speech", "speech_to_text"]),
            docs_url: docs("https://ppq.ai"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("cohere"),
            display_name: pt("Cohere"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["language", "embedding"]),
            docs_url: docs("https://docs.cohere.com"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("voyage"),
            display_name: pt("Voyage AI"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["embedding"]),
            docs_url: docs("https://docs.voyageai.com"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("elevenlabs"),
            display_name: pt("ElevenLabs"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["text_to_speech", "speech_to_text"]),
            docs_url: docs("https://elevenlabs.io/docs"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("deepgram"),
            display_name: pt("Deepgram"),
            requires_api_key: true,
            requires_base_url: false,
            modalities: types(&["text_to_speech", "speech_to_text"]),
            docs_url: docs("https://developers.deepgram.com/docs"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("ollama"),
            display_name: pt("Ollama"),
            requires_api_key: false,
            requires_base_url: true,
            modalities: types(&["language", "embedding"]),
            docs_url: docs("https://ollama.com"),
            env_configured: true,
        },
        ProviderInfo {
            name: pt("omlx"),
            display_name: pt("oMLX"),
            requires_api_key: false,
            requires_base_url: true,
            modalities: types(&["language", "embedding"]),
            docs_url: docs("https://github.com/omlx/omlx"),
            env_configured: true,
        },
        ProviderInfo {
            name: pt("azure"),
            display_name: pt("Azure OpenAI"),
            requires_api_key: true,
            requires_base_url: true,
            modalities: types(&["language", "embedding", "text_to_speech", "speech_to_text"]),
            docs_url: docs("https://learn.microsoft.com/azure/ai-services/openai"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("vertex"),
            display_name: pt("Google Vertex AI"),
            requires_api_key: true,
            requires_base_url: true,
            modalities: types(&["language", "embedding", "text_to_speech"]),
            docs_url: docs("https://cloud.google.com/vertex-ai/docs"),
            env_configured: false,
        },
        ProviderInfo {
            name: pt("openai_compatible"),
            display_name: pt("OpenAI Compatible"),
            requires_api_key: true,
            requires_base_url: true,
            modalities: types(&["language", "embedding", "text_to_speech", "speech_to_text"]),
            docs_url: None,
            env_configured: false,
        },
        ProviderInfo {
            name: pt("anthropic_compatible"),
            display_name: pt("Anthropic Compatible"),
            requires_api_key: true,
            requires_base_url: true,
            modalities: types(&["language"]),
            docs_url: None,
            env_configured: false,
        },
    ])
}
